### ISSUE TITLE
solved in doom-emacs, but...

### ISSUE THREAD

**Issue by OrionRandD** [martinbaillie/evil-motion-trainer#2]
Evil-motion-trainer is working in doom-Emacs.
But, keys  "j" and "k" do not work in org-mode  ".org" buffers...
I can still navigate using these keys.
evil-motion-trainer only complains in org-mode if I type "h" and "l" keys 
above my limit.
Can you reproduce this behaviour in an ".org" buffer?
Thx.

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(use-package! evil-motion-trainer
  :init
  (global-evil-motion-trainer-mode 1)
  :config
  (setq evil-motion-trainer-threshold 6)
  ;; (setq evil-motion-trainer-super-annoying-mode t)
  (emt-add-suggestion 'evil-next-line 'evil-avy-goto-char-timer)
  )

(map!
 :leader
 (:prefix-map ("t" . "toggle")
  :desc "Evil motion trainer" "t" #'evil-motion-trainer-mode))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

**Comment by martinbaillie** [comment]
Hi @OrionRandD would you mind updating and giving it another shot.

**Comment by OrionRandD** [comment]
@martinbaillie  I have update, but to no avail
But, I can live with it. 
After all it happens only in org files.
Other file extensions, it is working all right...

**Comment by OrionRandD** [comment]
> Hi @OrionRandD would you mind updating and giving it another shot.
Great! After opening Emacs for the second time after your upgrade.
It is working with org files!
Thx a lot ->   :)

**Comment by martinbaillie** [comment]
Great to hear

**Comment by OrionRandD** [comment]
> Great to hear

After upgrading Emacs to the latest version in debian.
Evil motion totally stopped working -> :( 
I think it is ralated to "cl-lib"
-> evil-motion-trainer -> simbol-p not defined...
-> then emacs --debug-init
shows errors related to cl-lib.
I commented
(require 'cl-lib) 
in the file, but the error still remained

**Comment by martinbaillie** [comment]
Sorry about that. I think you picked up a bust `master` commit. Hopefully fixed now.

**Comment by OrionRandD** [comment]
> Sorry about that. I think you picked up a bust `master` commit. Hopefully fixed now.

Back to work. Thx again
Solved :)
